// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyecto.Models;

#nullable disable

namespace proyecto.Migrations
{
    [DbContext(typeof(RhdbContext))]
    [Migration("20260728133256_gestion-finalizada")]
    partial class gestionfinalizada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuItemRol", b =>
                {
                    b.Property<int>("IdMenu")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdMenu", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("MenuItemRol");
                });

            modelBuilder.Entity("proyecto.Models.Categorium", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria")
                        .HasName("categoria_pkey");

                    b.HasIndex(new[] { "Nombre" }, "categoria_nombre_key")
                        .IsUnique();

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("proyecto.Models.Delivery", b =>
                {
                    b.Property<int>("IdDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDelivery"));

                    b.Property<decimal>("CostoEnvio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_envio");

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion_entrega");

                    b.Property<string>("EstadoEntrega")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_entrega")
                        .HasDefaultValueSql("'Pendiente'::character varying");

                    b.Property<DateTime?>("HoraEntrega")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hora_entrega");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hora_salida");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Referencia")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("referencia");

                    b.HasKey("IdDelivery")
                        .HasName("delivery_pkey");

                    b.HasIndex("IdUsuario");

                    b.HasIndex(new[] { "IdPedido" }, "delivery_id_pedido_key")
                        .IsUnique();

                    b.ToTable("delivery");
                });

            modelBuilder.Entity("proyecto.Models.DetalleMenuDiario", b =>
                {
                    b.Property<int>("IdDetalleMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_menu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleMenu"));

                    b.Property<int>("IdMenuDiario")
                        .HasColumnType("integer")
                        .HasColumnName("id_menu_diario");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.HasKey("IdDetalleMenu")
                        .HasName("detalle_menu_diario_pkey");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "IdMenuDiario", "IdProducto" }, "uq_menu_producto")
                        .IsUnique();

                    b.ToTable("detalle_menu_diario");
                });

            modelBuilder.Entity("proyecto.Models.DetallePedido", b =>
                {
                    b.Property<int>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetallePedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetallePedido")
                        .HasName("detalle_pedido_pkey");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "IdPedido", "IdProducto" }, "uq_pedido_producto")
                        .IsUnique();

                    b.ToTable("detalle_pedido");
                });

            modelBuilder.Entity("proyecto.Models.DetalleReserva", b =>
                {
                    b.Property<int>("IdDetalleReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_reserva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleReserva"));

                    b.Property<int>("IdMesa")
                        .HasColumnType("integer")
                        .HasColumnName("id_mesa");

                    b.Property<int>("IdReserva")
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    b.HasKey("IdDetalleReserva")
                        .HasName("detalle_reserva_pkey");

                    b.HasIndex(new[] { "IdMesa" }, "idx_detalle_reserva_mesa");

                    b.HasIndex(new[] { "IdReserva" }, "idx_detalle_reserva_reserva");

                    b.HasIndex(new[] { "IdReserva", "IdMesa" }, "uq_reserva_mesa")
                        .IsUnique();

                    b.ToTable("detalle_reserva");
                });

            modelBuilder.Entity("proyecto.Models.MenuDiario", b =>
                {
                    b.Property<int>("IdMenuDiario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_menu_diario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMenuDiario"));

                    b.Property<string>("MenuDia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("menu_dia");

                    b.HasKey("IdMenuDiario")
                        .HasName("menu_diario_pkey");

                    b.HasIndex(new[] { "MenuDia" }, "menu_diario_menu_dia_key")
                        .IsUnique();

                    b.ToTable("menu_diario");
                });

            modelBuilder.Entity("proyecto.Models.MenuItem", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_menu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMenu"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ruta");

                    b.HasKey("IdMenu");

                    b.ToTable("menu_item");
                });

            modelBuilder.Entity("proyecto.Models.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_mesa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMesa"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'Disponible'::character varying");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer")
                        .HasColumnName("numero_mesa");

                    b.HasKey("IdMesa")
                        .HasName("mesa_pkey");

                    b.HasIndex(new[] { "NumeroMesa" }, "mesa_numero_mesa_key")
                        .IsUnique();

                    b.ToTable("mesa");
                });

            modelBuilder.Entity("proyecto.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'Pendiente'::character varying");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdMesa")
                        .HasColumnType("integer")
                        .HasColumnName("id_mesa");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("TipoPedido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_pedido");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("IdPedido")
                        .HasName("pedido_pkey");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("proyecto.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdProducto")
                        .HasName("producto_pkey");

                    b.HasIndex(new[] { "IdCategoria" }, "idx_producto_categoria");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("proyecto.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReserva"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_personas");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'Pendiente'::character varying");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdReserva")
                        .HasName("reserva_pkey");

                    b.HasIndex(new[] { "IdUsuario" }, "idx_reserva_usuario");

                    b.ToTable("reserva");
                });

            modelBuilder.Entity("proyecto.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol")
                        .HasName("rol_pkey");

                    b.HasIndex(new[] { "Nombre" }, "rol_nombre_key")
                        .IsUnique();

                    b.ToTable("rol");
                });

            modelBuilder.Entity("proyecto.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<int?>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario")
                        .HasName("usuario_pkey");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Email" }, "usuario_email_key")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("MenuItemRol", b =>
                {
                    b.HasOne("proyecto.Models.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("IdMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("proyecto.Models.Delivery", b =>
                {
                    b.HasOne("proyecto.Models.Pedido", "IdPedidoNavigation")
                        .WithOne("Delivery")
                        .HasForeignKey("proyecto.Models.Delivery", "IdPedido")
                        .IsRequired()
                        .HasConstraintName("fk_delivery_pedido");

                    b.HasOne("proyecto.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Deliveries")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("fk_delivery_usuario");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("proyecto.Models.DetalleMenuDiario", b =>
                {
                    b.HasOne("proyecto.Models.MenuDiario", "IdMenuDiarioNavigation")
                        .WithMany("DetalleMenuDiarios")
                        .HasForeignKey("IdMenuDiario")
                        .IsRequired()
                        .HasConstraintName("fk_detalle_menu");

                    b.HasOne("proyecto.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetalleMenuDiarios")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("fk_detalle_menu_producto");

                    b.Navigation("IdMenuDiarioNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("proyecto.Models.DetallePedido", b =>
                {
                    b.HasOne("proyecto.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdPedido")
                        .IsRequired()
                        .HasConstraintName("fk_detalle_pedido");

                    b.HasOne("proyecto.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("fk_detalle_producto");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("proyecto.Models.DetalleReserva", b =>
                {
                    b.HasOne("proyecto.Models.Mesa", "IdMesaNavigation")
                        .WithMany("DetalleReservas")
                        .HasForeignKey("IdMesa")
                        .IsRequired()
                        .HasConstraintName("fk_detalle_reserva_mesa");

                    b.HasOne("proyecto.Models.Reserva", "IdReservaNavigation")
                        .WithMany("DetalleReservas")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("fk_detalle_reserva");

                    b.Navigation("IdMesaNavigation");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("proyecto.Models.Pedido", b =>
                {
                    b.HasOne("proyecto.Models.Mesa", "IdMesaNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdMesa")
                        .HasConstraintName("fk_pedido_mesa");

                    b.HasOne("proyecto.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("fk_pedido_usuario");

                    b.Navigation("IdMesaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("proyecto.Models.Producto", b =>
                {
                    b.HasOne("proyecto.Models.Categorium", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("fk_producto_categoria");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("proyecto.Models.Reserva", b =>
                {
                    b.HasOne("proyecto.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("fk_reserva_usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("proyecto.Models.Usuario", b =>
                {
                    b.HasOne("proyecto.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("fk_rol_usuario");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("proyecto.Models.Categorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("proyecto.Models.MenuDiario", b =>
                {
                    b.Navigation("DetalleMenuDiarios");
                });

            modelBuilder.Entity("proyecto.Models.Mesa", b =>
                {
                    b.Navigation("DetalleReservas");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("proyecto.Models.Pedido", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("proyecto.Models.Producto", b =>
                {
                    b.Navigation("DetalleMenuDiarios");

                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("proyecto.Models.Reserva", b =>
                {
                    b.Navigation("DetalleReservas");
                });

            modelBuilder.Entity("proyecto.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("proyecto.Models.Usuario", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Pedidos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
